defmodule GuildHall.Repo.Migrations.AttributesUniqueAndSeed do
  use Ecto.Migration

  alias GuildHall.Categories
  alias GuildHall.Attributes.Attribute

  def change do
    create(
      unique_index(:attributes, ["lower(name)", :category_id], name: :unique_name_in_category)
    )

    flush()

    execute(fn ->
      [
        {"AfterEffects", :technology},
        {"Analytics", :technology},
        {"Android", :technology},
        {"Angular", :technology},
        {"AwsEc2", :technology},
        {"AwsElb", :technology},
        {"AwsS3", :technology},
        {"AwsSes", :technology},
        {"AwsSqs", :technology},
        {"Balsamiq", :technology},
        {"BambooRabbitMQ", :technology},
        {"Blender", :technology},
        {"Celery", :technology},
        {"CircleCi", :technology},
        {"Csharp", :technology},
        {"DefaultTechn", :technology},
        {"Docker", :technology},
        {"Elixir", :technology},
        {"Erlang", :technology},
        {"Eve", :technology},
        {"Experience", :technology},
        {"Figma", :technology},
        {"Flask", :technology},
        {"Flowmapp", :technology},
        {"FramerX", :technology},
        {"Fsharp", :technology},
        {"FullStory", :technology},
        {"Haskell", :technology},
        {"Illustrator", :technology},
        {"Indesign", :technology},
        {"Invision", :technology},
        {"iOS", :technology},
        {"Java", :technology},
        {"Jenkins", :technology},
        {"Kotlin", :technology},
        {"Lambdas", :technology},
        {"Lightroom", :technology},
        {"Mixpanel", :technology},
        {"MsAspMcv", :technology},
        {"MsAspNet", :technology},
        {"MsSql", :technology},
        {"MsWpf", :technology},
        {"NodeJs", :technology},
        {"ObjectiveC", :technology},
        {"Phoenix", :technology},
        {"Photoshop", :technology},
        {"Plivo", :technology},
        {"PostgreSQL", :technology},
        {"Premiere", :technology},
        {"Procreate", :technology},
        {"Python", :technology},
        {"React", :technology},
        {"ReactNative", :technology},
        {"Reaper", :technology},
        {"Redux", :technology},
        {"Segment", :technology},
        {"Sketch", :technology},
        {"Sonar", :technology},
        {"Swift", :technology},
        {"Unity", :technology},
        {"WacomTablets", :technology},
        {"Wix", :technology},
        {"Xamarin", :technology},
        {"Zeplin", :technology},
        {"Cloudinary", :technology},
        {"UI/UX", :technology},
        {"3D Modelling", :technology},
        {"2D Illustration", :technology},
        {"UV Mapping", :technology},
        {"AR/VR", :technology},
        {"Material UI", :technology},
        {"Principle", :technology},
        {"Google Analytics", :technology},
        {"Stripe", :technology},
        {"Trello", :technology},
        {"Slack", :technology},
        {"Google Tools", :technology},
        {"Javascript", :technology},
        {"MockFlow", :technology},
        {"Pen and Paper", :technology},
        {"Java Swing", :technology},
        {"IntelliJ Idea", :technology},
        {"Cucumber", :technology},
        {"Testcafe", :technology},
        {"Jira", :technology},
        {"GitHub", :technology},
        {"Firebase", :technology},
        {"AWS", :technology},
        {"C#", :technology},
        {"Multi-threading", :technology},
        {"Dagger", :technology},
        {"Cordova", :technology},
        {"HTML", :technology},
        {"CSS", :technology},
        {"SQL", :technology},
        {"PHP", :technology},
        {"ES6", :technology},
        {"Typescript", :technology},
        {"FlexBox", :technology},
        {"Stripe Integration", :technology},
        {"Rethink DB", :technology},
        {"RXJS", :technology},
        {"GraphQL", :technology},
        {"Raspberry PI", :technology},
        {"MONO/RASPBIAN", :technology},
        {"Web/Windows Services", :technology},
        {"SSIS", :technology},
        {"SSRS", :technology},
        {"SSAS", :technology},
        {"Sisense", :technology},
        {"Tableau", :technology},
        {"Knowi", :technology},
        {"QLIK Sense", :technology},
        {"PowerBI", :technology},
        {"DBT", :technology},
        {"Snowflake", :technology},
        {"Data Vault", :technology},
        {"Methodology", :technology},
        {"Excel", :technology},
        {"Elm", :technology},
        {"Cronofy", :technology},
        {"Jade", :technology},
        {"ExpressJS", :technology},
        {"MySQL", :technology},
        {"Blockchain", :technology},
        {"Solidarity", :technology},
        {"Zbrush", :technology},
        {"Intuos Pro 5", :technology},
        {"Bamboo", :technology},
        {"Intuos P&T", :technology},
        {"DynamoDB", :technology},
        {"Kafka", :technology},
        {"RabbitMQ", :technology},
        {"Cowboy", :technology},
        {"SPLUNK", :technology},
        {"NGINX", :technology},
        {"Datadog", :technology},
        {"Babel", :technology},
        {"ExpoIO", :technology},
        {"Oracle", :technology},
        {"MongoDB", :technology},
        {"Custom Web Components", :technology},
        {"Styled Systems", :technology},
        {"Tailwind CSS", :technology},
        {"SystemUI", :technology},
        {"NPM", :technology},
        {"Jest", :technology},
        {"Threading and Parallel Programming", :technology},
        {"R.Net Framework", :technology},
        {"WinForms", :technology},
        {"DEVEXPRESS", :technology},
        {"Sockets", :technology},
        {"F#", :technology},
        {".Net Framework", :technology},
        {"Functional programming techniques", :technology},
        {"Crystal reports", :technology},
        {"Microsoft Sharepoint", :technology},
        {"Project Server", :technology},
        {"JQuery", :technology},
        {"Microsoft Technologies Stack", :technology},
        {"Appium", :technology},
        {"Agile Methodologies", :technology},
        {"Manual Testing", :technology},
        {"Test Reports", :technology},
        {"Functional testing", :technology},
        {"Smoke testing", :technology},
        {"FADV", :technology},
        {"APPTEX", :technology},
        {"Arc", :technology},
        {"LiveView", :technology},
        {"Flow", :technology},
        {"Ecto", :technology},
        {"Scrapping", :technology},
        {"UNIRX", :technology},
        {"Storyboard", :technology},
        {"MVVM", :technology},
        {"Rest API", :technology},
        {"COCOAPODS", :technology},
        {"FastLane", :technology},
        {"AlamoFire", :technology},
        {"Unit tests", :technology},
        {"Spring", :technology},
        {"Microservices", :technology},
        {"Kubernetes", :technology},
        {"Redis", :technology},
        {"Retrofit", :technology},
        {"Room", :technology},
        {"Scandit", :technology},
        {"ZPL", :technology},
        {"Prolog", :technology},
        {"SCSS", :technology},
        {"Rust", :technology},
        {"Scala", :technology},
        {"ViteJS", :technology},
        {"Django", :technology},
        {"Development", :department},
        {"HR", :department},
        {"Product management", :department},
        {"UI/UX", :department},
        {"Testing", :department},
        {"Persevering", :soft_skill},
        {"Ambitious", :soft_skill},
        {"Solution oriented", :soft_skill},
        {"Solution focused", :soft_skill},
        {"Digital painter", :soft_skill},
        {"Team player", :soft_skill},
        {"Public speaker", :soft_skill},
        {"Father of 3", :soft_skill},
        {"Bike rider", :soft_skill},
        {"Ping pong lover", :soft_skill},
        {"Beer searcher", :soft_skill},
        {"Kids trainer", :soft_skill},
        {"Tech lead", :soft_skill},
        {"Artist", :soft_skill},
        {"Very organised", :soft_skill},
        {"Problem solving oriented", :soft_skill},
        {"Cycling addict", :soft_skill},
        {"Analytical", :soft_skill},
        {"Problem solver", :soft_skill},
        {"Sports addict", :soft_skill},
        {"Eagerness to learn", :soft_skill},
        {"Perfectionist", :soft_skill},
        {"Gamer", :soft_skill},
        {"Relationship builder", :soft_skill},
        {"Ownership/autonomy", :soft_skill},
        {"Poker player", :soft_skill},
        {"Morning person", :soft_skill},
        {"Bike runner", :soft_skill},
        {"Painter", :soft_skill},
        {"Hark worker", :soft_skill},
        {"Travel lover", :soft_skill},
        {"Analytical thinker", :soft_skill},
        {"Father of two", :soft_skill},
        {"Vegetarian", :soft_skill},
        {"Wood crafting", :soft_skill},
        {"Never misses a festival", :soft_skill},
        {"Ski & hiking lover", :soft_skill},
        {"Meticulous", :soft_skill},
        {"Archery", :soft_skill},
        {"Eye-sharpness", :soft_skill},
        {"Complex feature testing", :soft_skill},
        {"Calm personality", :soft_skill},
        {"Gardening lover", :soft_skill},
        {"Traveler", :soft_skill},
        {"Reader", :soft_skill},
        {"Motorbike rider", :soft_skill},
        {"Car lover", :soft_skill},
        {"Software passionate", :soft_skill},
        {"Rally lover", :soft_skill},
        {"Adrenaline addict", :soft_skill},
        {"UI/UX", :hard_skill},
        {"3D Modelling", :hard_skill},
        {"2D Design", :hard_skill},
        {"Detail oriented", :hard_skill},
        {"Problem solving", :hard_skill},
        {"Attention to details", :hard_skill},
        {"Pitching", :hard_skill},
        {"Planning", :hard_skill},
        {"French and Spanish speaker", :hard_skill},
        {"Team management", :hard_skill},
        {"Team player", :hard_skill},
        {"Fast learner", :hard_skill},
        {"Creativity", :hard_skill},
        {"Passionate", :hard_skill},
        {"Client communication", :hard_skill},
        {"Analytical", :hard_skill},
        {"Mentoring", :hard_skill},
        {"Coaching", :hard_skill},
        {"Software development", :hard_skill},
        {"Solution oriented", :hard_skill},
        {"Well organised", :hard_skill},
        {"Reliable", :hard_skill},
        {"Hark worker", :hard_skill},
        {"Sense of humour", :hard_skill},
        {"Proactive", :hard_skill},
        {"Data analysis", :hard_skill},
        {"Data modeling", :hard_skill},
        {"Database development", :hard_skill},
        {"Database administration", :hard_skill},
        {"Database maintenance", :hard_skill},
        {"Data warehousing", :hard_skill},
        {"DB/Query performance tuning", :hard_skill},
        {"Organisational skills", :hard_skill},
        {"Good communicator", :hard_skill},
        {"Teaching", :hard_skill},
        {"Functional programming", :hard_skill},
        {"Perfectionist", :hard_skill},
        {"Innovative", :hard_skill},
        {"Leading teams", :hard_skill},
        {"Autonomy", :hard_skill},
        {"Ownership", :hard_skill},
        {"Relationship builder", :hard_skill},
        {"Branding", :hard_skill},
        {"Graphic design", :hard_skill},
        {"Painting", :hard_skill},
        {"Bike rider", :hard_skill},
        {"Morning person", :hard_skill},
        {"Jogging", :hard_skill},
        {"Clean code", :hard_skill},
        {"Knowledge sharing", :hard_skill},
        {"Analytical thinking", :hard_skill},
        {"Architecture", :hard_skill},
        {"Problem solver", :hard_skill},
        {"Manual Testing", :hard_skill},
        {"Automation testing", :hard_skill},
        {"Growth minset", :hard_skill},
        {"Health tech", :industry},
        {"Fintech", :industry},
        {"Banking", :industry},
        {"Educational games", :industry},
        {"Photography", :industry},
        {"Games", :industry},
        {"Chat bots", :industry},
        {"Food", :industry},
        {"AR/VR", :industry},
        {"Remote working", :industry},
        {"Biotech", :industry},
        {"Stock markets", :industry},
        {"Real estate", :industry},
        {"Smart city", :industry},
        {"Workforce management", :industry},
        {"Communication", :industry},
        {"Education", :industry},
        {"Marketing", :industry},
        {"Digital marketing", :industry},
        {"Advertising", :industry},
        {"Finance and accounting", :industry},
        {"Staffing and recruiting", :industry},
        {"Social apps", :industry},
        {"Services", :industry},
        {"Ride sharing", :industry},
        {"Beauty", :industry},
        {"Volunteering", :industry},
        {"Entertainment", :industry},
        {"Tool manufacturing", :industry},
        {"Tech consulting", :industry},
        {"Oil and gas", :industry},
        {"Events", :industry},
        {"Gardens", :industry},
        {"Production", :industry},
        {"Retail", :industry},
        {"Tabacco", :industry},
        {"Instant messaging", :industry},
        {"SVN", :technology},
        {"WEB API", :technology},
        {"1c: Enterprise", :technology}
      ]
      |> Enum.reduce(%{}, fn {name, category_atom}, named_categories ->
        named_categories =
          Map.put_new_lazy(named_categories, category_atom, fn ->
            Categories.get_named_category(category_atom)
          end)

        repo().insert!(
          %Attribute{
            name: name,
            category: Map.fetch!(named_categories, category_atom)
          },
          on_conflict: :nothing
        )

        named_categories
      end)
    end)
  end
end
