name: TEST

on:
  push:

jobs:
  test:
    name: Run the tests
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      APP_NAME: guild_hall_test

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: guild_hall
          POSTGRES_PASSWORD: guild_hall
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.12.1' # Define the elixir version [required]
          otp-version: '23.2.1' # Define the erlang/OTP version [required]
      - name: Set version environment variable
        run: echo "APP_VSN=$(grep 'version:' mix.exs | cut -d '"' -f2 | tail -1 )" >> $GITHUB_ENV
      - name: Get dependencies and compile
        run: mix do clean, deps.get --only $MIX_ENV, compile --force
      - name: Run the tests
        run: mix test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: _build/test/lib/guild_hall/test-report.xml
